# YAML - minipopS CMS.

---
site: 
    blog: 
        title: Jacky Chazalette
        subtitle: Un site sous miniPops
        description: Un site sous miniPops
        keywords: minipops, cms, minipopscms
        author: Jacky Chazalette
        author_email: ~
        copyright: @2015 - Propulsé par miniPops
        lang: fr
        theme: default
        robots: index
    setting: 
        urlrewrite: enable
        timezone: Europe/London
        date_format: F j, Y
        time_format: g:i a
        api_key: 9pJ?b3sduAwFWPL+qe
        api_keysalt: 1W.RoC-*(nV9fF
    optimize: 
        files: 
            html: false
            css: false
            js: false
        lazyload: 
            images: false
        cache: 
            cached: false
            pages_no_cache: ~
            theme: default
    customize: 
        primary_menu: ~
...
