# generate by mini-pops

title: miniPops

----

subtitle: Un site sous miniPops

----

description: Un site sous miniPops

----

keywords: minipops, cms, minipopscms

----

author: stephen deletang

----

copyright: @2015 -  Propulsé par miniPops

----

lang: fr

----

url_rewrite: enable

----

plugins: // List of the plugins separator comma: mp_cache, mp_google

----

theme: default

----

timezone: Europe/Paris

----

api-key: GFg#drbVMeR:4L(cntZEfk*,YQ?XzsDS

----

api-keysalt: pF@sQ=;tAEeV(+LuHPDg)T!ao6z^28Jj

----
