# YAML - minipopS CMS.

---
site: 
    blog: 
        title: miniPops
        subtitle: Un site sous miniPops
        description: Un site sous miniPops
        keywords: minipops, cms, minipopscms
        author: stephen deletang
        author_email: ~
        copyright: @2015 -  Propulsé par miniPops
        lang: fr
        theme: default
        robots: index
    setting: 
        urlrewrite: enable
        timezone: Europe/London
        date_format: F j, Y
        time_format: g:i a
        api_key: GgcO)#WTFiK*z&st,ar(w.59H@!qk_VP
        api_keysalt: U!J(tCN=4a0vSFKrWMisfy92LA+Z-.dp
    plugins: 
        active_plugins: ~
    optimize: 
        files: 
            html: false
            css: false
            js: false
        lazyload: 
            images: false
        cache: 
            cached: false
            pages_no_cache: ~
            theme: default
    customize: 
        primary_menu: ~
...
