# YAML - minipopS CMS.

---
site: 
    blog: 
        title: miniPops
        subtitle: Un site sous miniPops
        description: Un site sous miniPops
        keywords: minipops, cms, minipopscms
        author: stephen deletang
        copyright: @2015 -  Propulsé par miniPops
        lang: fr
        theme: default
    setting: 
        urlrewrite: enable
        timezone: 1
        date_format: F j, Y
        time_format: g:i a
        api_key: @HLSdhiA?-Kv=u8ZyqB.5W4$ajNr01bk
        api_keysalt: TyS.KLwN?UOJAlsHGiE@6d(^Vx$+rthg
    optimize: 
        cache: true
        pages_no_cache: ~
        cache_theme: default
    customize: 
        primary_menu: ~
...
