# YAML - minipopS CMS.

---
site: 
    blog: 
        title: miniPops
        subtitle: Un site sous miniPops
        description: Un site sous miniPops
        keywords: minipops, cms, minipopscms
        author: stephen deletang
        copyright: @2015 -  Propulsé par miniPops
        lang: fr
        theme: default
    setting: 
        urlrewrite: disable
        timezone: Europe/London
        date_format: F j, Y
        time_format: g:i a
        api_key: ,bAmsCQzZ=7.WPqKe9Rf*JiyH+Bg0IwO
        api_keysalt: S!4wd+(8T&o9AVByP-b,@.6EYuJtR2h)
    optimize: 
        cache: true
        pages_no_cache: ~
        cache_theme: default
    customize: 
        primary_menu: ~
...
