# YAML - minipopS CMS.

---
site: 
    blog: 
        title: miniPops
        subtitle: Un site sous miniPops
        description: Un site sous miniPops
        keywords: minipops, cms, minipopscms
        author: stephen deletang
        copyright: @2015 -  Propulsé par miniPops
        lang: fr
        theme: default
    setting: 
        urlrewrite: disable
        timezone: 1
        date_format: F j, Y
        time_format: g:i a
        api_key: @HLSdhiA?-Kv=u8ZyqB.5W4$ajNr01bk
        api_keysalt: TyS.KLwN?UOJAlsHGiE@6d(^Vx$+rthg
    optimize: 
        files: 
            html: false
            css: false
            js: false
        lazyload: 
            images: false
        cache: 
            cached: false
            pages_no_cache: ~
            theme: default
    customize: 
        primary_menu: ~
    security: 
        firewall: 
            bad_ips: ~
            bad_user_agents: ~
            bad_referrers: ~
            active: true
...
